/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestPublishGradleGithubPackage;

public class Library {
    public void printMessage() {
        System.out.println("Hello From Library!");
    }
}
